blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # post views
    # path('', views.post_list, name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
# Create your models here.
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class PublishedManager(models.Manager):
    '''customized manager to retrieve all posts with the published status'''
    def get_queryset(self):
        '''The get function of the customized manager'''
        return super().get_queryset().filter(satus='published')



class Post (models.Model):
    '''This is Blog's Post Data Schema'''
    
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name = 'blog_posts'
    )
    # testField = models.CharField(max_length=250, default='AnasKhanTesting')
    body = models.TextField(default='Default Body')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    satus = models.CharField(max_length=10,
                             choices=STATUS_CHOICES,
                             default='draft')

    objects = models.Manager() # The default manager.
    
    # this published custom manager was conflicting with 
    # the published variable defined above. Thus, I changed 
    # it to objects_published
    objects_published = PublishedManager() #my custom manager
    
    class Meta:
        '''Add the metadata'''
        ordering = ('-publish',)
        
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        '''To build the canonical URL for Post objects'''
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])

blog/forms.py
from django import forms

class EmailPostForm(forms.Form):
    '''Django from created using Form class'''
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)

blog/views.py
# Create your views here.
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger
# from django.views import ListView
from django.views.generic.list import ListView
from .forms import EmailPostForm
from django.core.mail import send_mail

def post_list(request):
    '''To (render) list all the published posts'''
    #posts = Post.objects_published.all()
    object_list = Post.objects_published.all()
    paginator = Paginator(object_list, 4) # 4 posts in each page
    page = request.GET.get('page')
    
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        #if page is not correct then reflect the first page
        posts = paginator.page(1)
    except EmptyPage:
        #if page out of range then the relect the last page
        posts = paginator.page(paginator.num_pages)    
    return render(request,
                  'blog/post/list.html',
                  {'posts':posts})
    
def post_detail(request, year, month, day, post):
    '''To display a single post'''
    post = get_object_or_404(Post,  slug=post,
                                    satus='published',
                                    publish__year=year,
                                    publish__month=month,
                                    publish__day=day)
    return render(request, 'blog/post/detail.html', {'post':post}) 

class PostListView(ListView):
    queryset = Post.objects_published.all()
    context_object_name = 'posts'
    paginate_by = 4
    template_name = 'blog/post/list.html'
    
def post_share(request, post_id):
    # Get the post using the id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    
    # if the data has been posted
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # All the form's field passed validation
            cd = form.cleaned_data
            # Send the Email Now
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you to read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                        f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'f14365fbd2994a3f8110@mailspons.com', [cd['to']])
            sent = True
            
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', 
                  {'post':post, 'form':form, 'sent':sent})

blog/templates/blog/base.html
<!-- This is the base template using the template tags -->
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static "css\blog.css" %}" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    </head>
    <body>
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
        <div id="sidebar">
            <h2>A Sample End to End Blogging Application by Anas Khan </h2>
            <p>The following Django 3 features were learned while developing this practice project:</p>
            <ul>
                <li>Phase-1</li>
                <ul>
                    <li>Creating a Django application</li>
                    <li>Designing the blog data schema (models.py)</li>
                    <li>Activating and applying migrations of the Model</li>
                </ul>
                <li>Phase-2</li>
                <ul>
                    <li>Creating a custom adminsitration site</li>
                    <li>Creating a superuser</li>
                </ul>
                <li>Phase-3</li>
                <ul>
                    <li>Retrieving information using Query Sets via Django ORM (Object-Relational Mapper)</li>
                    <li>Creating a custom model manager</li>
                </ul>
                <li>Phase-4</li>
                <ul>
                    <li>Building list and details views</li>
                    <li>Adding URL patters to the views</li>
                </ul>
                <li>Phase-5</li>
                <ul>
                    <li>Creating templates for my views by using Template Tags, Variables and Filters</li>
                    <li>Adding Pagination</li>
                </ul>
            </ul>
        </div>
    </body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{post.title}}</h1>
    <p class="date">
        Published {{post.publish}} by {{post.author}}
    </p>
    {{post.body | linebreaks}}
    <p>
        <a href="{% url "blog:post_share" post.id %}"></a>
        Share this post
    </p>
{% endblock %}

blog/templates/blog/post/list.html
<!-- This is the list template -->
{% extends "blog/base.html" %}

{% block title %}AnasKhan-Blog{% endblock %}

{% block content %}
    <h1>Welcome To AnasKhan's Blog</h1>
        {% for post in posts %}
            <h2>
                <!-- Using the Template Variables -->
                <a href="{{ post.get_absolute_url }}">
                    {{post.title}}
                </a>
            </h2>
            <p class="date">
                <!-- Using the Template Variables -->
                Published {{ post.publish }} by {{ post.author }}
            </p>
            <!-- Using the Template Filters -->
            {{post.body | truncatewords:30 | linebreaks }}
        {% endfor %}
        <!-- {% include "pagination.html" with page=posts %} -->
        {% include "pagination.html" with page=page_obj %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail sent successfully</h1>
        <p>
            "{{post.title}}" was successfully sent to {{form.cleaned_data.to}}.
        </p>
    {% else %}
        <h1>Share "{{post.title}}" by e-mail</h1>
        <form method="post">
            {{form.as_p }}
            {% csrf token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{page.number}} of {{page.paginator.num_pages}}
        </span>
        {% if page.has_next %}
            <a href="?page={{page.next_page_number}}">Next</a>
        {% endif %}
    </span>
</div>